credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: abc # Replace with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: def # Replace with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be a string
  name: random_cookie_name
